import 'package:get/get.dart';

class AppMessages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'pt_BR': {
      'app_language': 'Português',
      'app_enable': 'Habilitado',
      'app_desable': 'Desabilitado',
      'app_again': 'Tentar novamente',
      'app_permision1': 'Para continuar, precisamos de acesso aos seus arquivos de áudio',
      'home_tab1': 'Músicas',
      'home_tab2': 'Pastas',
      'home_tab3': 'Playlist',
      'home_not_tab1': 'Sem músicas',
      'home_not_tab2': 'Sem pastas',
      'home_not_tab3': 'Sem playlist',
      'playlist1': 'Recentes',
      'cloud_error1': 'Sem Resultados',
      'setting_title': 'Configurações',
      'setting_ignore': 'Ignorar áudio menores que: @seconds segundos',
      'setting_mode': 'Modo escuro',
    },
    'en_US': {
      'app_language': 'English',
      'app_enable': 'Enable',
      'app_desable': 'Desable',
      'app_again': 'Try again',
      'app_permision1': 'To continue, we need access to your audio files',
      'home_tab1': 'Music',
      'home_tab2': 'Folders',
      'home_tab3': 'Playlist',
      'home_not_tab1': 'No music',
      'home_not_tab2': 'No folders',
      'home_not_tab3': 'No playlist',
      'playlist1': 'Recents',
      'cloud_error1': 'No Results',
      'setting_title': 'Settings',
      'setting_ignore': 'Ignore audio shorter than: @seconds seconds',
      'setting_mode': 'Mode dark',
    },
    'es_ES': {
      'app_language': 'Español',
      'app_enable': 'habilitado',
      'app_desable': 'deshabilitado',
      'app_again': 'Intentar otra vez',
      'app_permision1': 'Para continuar, necesitamos acceso a sus archivos de audio',
      'home_tab1': 'Música',
      'home_tab2': 'Carpetas',
      'home_tab3': 'Lista de reproducción',
      'home_not_tab1': 'Sin música',
      'home_not_tab2': 'Sin carpetas',
      'home_not_tab3': 'Sin lista de reproducción',
      'playlist1': 'Recientes',
      'cloud_error1': 'No hay resultados',
      'setting_title': 'Configuraciones',
      'setting_ignore': 'Ignorar audio más corto de: @seconds segundos',
      'setting_mode': 'Modo oscuro',
    },
  };
}
