import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslations extends Translations {
  
  @override
  Map<String, Map<String, String>> get keys => {
    'pt_BR': {
      'app_language': 'Português',
      'app_enable': 'Habilitado',
      'app_disable': 'Desabilitado',
      'app_again': 'Tentar novamente',
      'app_search': 'Pesquisar',
      'app_permision1': 'Para continuar, precisamos de acesso aos seus arquivos de áudio',
      'home_tab1': 'Músicas',
      'home_tab2': 'Pastas',
      'home_tab3': 'Album',
      'home_not_tab1': 'Sem músicas',
      'home_not_tab2': 'Sem pastas',
      'home_not_tab3': 'Sem Album',
      'crud_sheet1': 'Adicionar a Playlist',
      'crud_sheet2': 'Excluir Música',
      'crud_sheet3': 'Editar Música',
      'crud_sheet_dialog_1': 'Cancelar',
      'crud_sheet_dialog_2': 'Confirmar',
      'crud_sheet_dialog_3': 'Título',
      'edit_title': 'Título',
      'edit_artist': 'Artista',
      'edit_image': 'Imagem',
      'edit_save': 'Salvando',
      'playlist1': 'Recentes',
      'playlist2': 'Excluir Playlist?',
      'cloud_error1': 'Sem Resultados',
      'setting_title': 'Configurações',
      'setting_ignore': 'Ignorar áudio menores que: @seconds segundos',
      'setting_mode': 'Modo escuro',
      'setting_equalizer': 'Equalizador',
      'setting_language': 'Idioma',
      'setting_sort': 'Ordenar',
      'setting_sort1': 'Ordenar de A a Z',
      'setting_sort2': 'Ordenar ultimos adicionados',
      'setting_sort3': 'Ordenar maior duração',
      'setting_reload': 'Recarregar',
      'setting_reset': 'Resetar equalizador',
      'equalizer_frequency1': 'Grave',
      'equalizer_frequency2': 'Agudo',
    },
    'en_US': {
      'app_language': 'English',
      'app_enable': 'Enable',
      'app_disable': 'Desable',
      'app_again': 'Try again',
      'app_search': 'Search',
      'app_permision1': 'To continue, we need access to your audio files',
      'home_tab1': 'Songs',
      'home_tab2': 'Folders',
      'home_tab3': 'Album',
      'home_not_tab1': 'No songs',
      'home_not_tab2': 'No folders',
      'home_not_tab3': 'No Album',
      'crud_sheet1': 'Add to Playlist',
      'crud_sheet2': 'Delete Song',
      'crud_sheet3': 'Edit Song',
      'crud_sheet_dialog_1': 'Cancel',
      'crud_sheet_dialog_2': 'Confirm',
      'crud_sheet_dialog_3': 'Title',
      'edit_title': 'Title',
      'edit_artist': 'Artist',
      'edit_image': 'Image',
      'edit_save': 'Saving',
      'playlist1': 'Recents',
      'playlist2': 'Delete Playlist?',
      'cloud_error1': 'No Results',
      'setting_title': 'Settings',
      'setting_ignore': 'Ignore audio shorter than: @seconds seconds',
      'setting_mode': 'Mode dark',
      'setting_equalizer': 'Equalizer',
      'setting_language': 'Language',
      'setting_sort': 'Sort',
      'setting_sort1': 'Sort by A to Z',
      'setting_sort2': 'Sort by most recently added',
      'setting_sort3': 'Sort by longest duration',
      'setting_reload': 'Reload',
      'setting_reset': 'Reset equalizer',
      'equalizer_frequency1': 'Low',
      'equalizer_frequency2': 'High',
    },
    'es_ES': {
      'app_language': 'Español',
      'app_enable': 'habilitado',
      'app_disable': 'deshabilitado',
      'app_again': 'Intentar otra vez',
      'app_search': 'Buscar',
      'app_permision1': 'Para continuar, necesitamos acceso a sus archivos de audio',
      'home_tab1': 'Música',
      'home_tab2': 'Carpetas',
      'home_tab3': 'Album',
      'home_not_tab1': 'Sin música',
      'home_not_tab2': 'Sin carpetas',
      'home_not_tab3': 'Album',
      'crud_sheet1': 'Agregar a lista de reproducción',
      'crud_sheet2': 'Eliminar música',
      'crud_sheet3': 'Editar música',
      'crud_sheet_dialog_1': 'Cancelar',
      'crud_sheet_dialog_2': 'Confirmar',
      'crud_sheet_dialog_3': 'Título',
      'edit_title': 'Título',
      'edit_artist': 'Artista',
      'edit_image': 'Imagen',
      'edit_save': 'Ahorro',
      'playlist1': 'Recientes',
      'playlist2': '¿Eliminar lista de reproducción?',
      'cloud_error1': 'No hay resultados',
      'setting_title': 'Configuraciones',
      'setting_ignore': 'Ignorar audio más corto de: @seconds segundos',
      'setting_mode': 'Modo oscuro',
      'setting_equalizer': 'Ecualizador',
      'setting_language': 'Idioma',
      'setting_sort': 'Clasificar',
      'setting_sort1': 'Ordenar de A a Z',
      'setting_sort2': 'Ordenar por los más recientemente añadidos',
      'setting_sort3': 'Ordenar por la duración más larga',
      'setting_reload': 'Recargar',
      'setting_reset': 'Restablecer ecualizador',
      'equalizer_frequency1': 'Bajo',
      'equalizer_frequency2': 'Agudo',
    },
  };
}
