name: playerhub
description: "The ultimate offline music player! Listen to your favorite songs without an internet connection, with high audio quality and an intuitive interface. Organize your tracks, adjust the sound with the equalizer and enjoy a limitless music experience."
publish_to: 'none'
version: 1.4.12+27

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  get: 4.6.6
  permission_handler: 11.3.1
  flutter_launcher_icons: 0.13.1
  audio_service: 0.18.15
  on_audio_query: 2.9.0
  just_audio: 0.9.39
  rxdart: 0.28.0
  just_audio_platform_interface: 4.3.0
  shared_preferences: 2.3.1
  device_info_plus: 10.1.2
  # connectivity_plus: 6.0.5
  path_provider: 2.1.4
  flutter_phoenix: 1.1.1
  equalizer_flutter: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter_launcher_icons:
  android: true
  image_path: "fastlane/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "fastlane/icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/lowpoly_blue.jpg
    - assets/images/lowpoly_green.jpg
    - assets/images/lowpoly_red.jpg
    
    - assets/fonts/OpenSans-OFL.txt

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
