name: player_hub
description: >-
  The ultimate offline music player!
  Listen to your favorite songs without an internet connection,
  with high audio quality and an intuitive interface.
  Organize your tracks, adjust the sound with the equalizer and enjoy a limitless music experience.
publish_to: 'none'
version: 1.8.72+119

environment:
  sdk: '>=3.4.4 <4.0.0' # current is: 3.5.3
  flutter: '>= 3.24.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  helper_hub:
    git:
      url: https://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@github.com/LucasLixo/Helper-Hub.git
      ref: 0.2.23
  get: 4.6.6
  permission_handler: 11.3.1
  flutter_launcher_icons: 0.14.1
  audio_service: 0.18.15
  on_audio_query: 2.9.0
  just_audio: 0.9.41
  just_audio_background:
    path: packages/just_audio_background
    version: any
  just_audio_platform_interface: 4.3.0
  shared_preferences: 2.3.2
  device_info_plus: 10.1.2
  path_provider: 2.1.4
  flutter_phoenix: 1.1.1
  equalizer_flutter: 0.0.1
  home_widget: 0.7.0
  share_plus: 9.0.0
  file_picker: 8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

platforms:
  android:

flutter_launcher_icons:
  android: true
  image_path: "fastlane/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "fastlane/icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/low_poly_blue.jpg
    - assets/images/low_poly_green.jpg
    - assets/images/low_poly_red.jpg

    - assets/images/high_poly_blue.jpg
    - assets/images/high_poly_green.jpg
    - assets/images/high_poly_red.jpg

    - assets/licenses/OpenSans-OFL.txt

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
