name: helper_hub
description: "A new Flutter plugin project."
version: 0.2.24
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>= 3.24.3'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
