// pages
export 'package:player_hub/app/pages/wait/wait_page.dart';
export 'package:player_hub/app/pages/splash/splash_page.dart';
export 'package:player_hub/app/pages/home/home_page.dart';
export 'package:player_hub/app/pages/setting/setting_page.dart';
export 'package:player_hub/app/pages/details/details_page.dart';
export 'package:player_hub/app/pages/edit/edit_page.dart';
export 'package:player_hub/app/pages/search/search_page.dart';
export 'package:player_hub/app/pages/playlist/playlist_page.dart';
export 'package:player_hub/app/pages/equalizer/equalizer_page.dart';
export 'package:player_hub/app/pages/selection/selection_add_page.dart';
export 'package:player_hub/app/pages/selection/selection_remove_page.dart';
