name: just_audio_background
description: An add-on for just_audio that supports background playback and media notifications.
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio_background
version: 0.0.1-beta.13
topics:
  - audio
  - sound
  - player
  - background

environment:
  sdk: '>=3.4.4 <4.0.0' # current is: 3.5.3
  flutter: '>= 3.24.3'

dependencies:
  just_audio_platform_interface: ^4.3.0
  # just_audio_platform_interface:
  #   path: ../just_audio_platform_interface
  audio_service: 0.18.15
  audio_session: ^0.1.20
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0
  rxdart: '>=0.26.0 <0.29.0'

dev_dependencies:
  flutter_lints: 5.0.0
